### PR TITLE
interface improvement. bug fixes. feature flags

### LINKED ISSUE #10: Unclear consumer declaration interface and implementation.
The current implementation of the `kafka_consumer` macro can be a bit unclear to use or debug. Now, it works as follows: 
```rust
let consumer = kafka_consumer!(
    topic = KafkaTopic {
        name: "test".to_string(),
        content_type: ContentType::Json
    },
    dlq_topic = KafkaTopic {
        name: "test-dlq".to_string(),
        content_type: ContentType::Json
    },
    consumer_group_id = "test-group",
    bootstrap_servers = bootstrap_servers,
    handlers = [
        EntityCreatedEventHandler -> EntityCreatedEventHandler {}
    ]
);
```

However it would be much simpler to maintain if the `handlers` definitions match a little bit how Rust declares new variables. That is:

```rust
let consumer = kafka_consumer!(
    topic = KafkaTopic {
        name: "test".to_string(),
        content_type: ContentType::Json
    },
    dlq_topic = KafkaTopic {
        name: "test-dlq".to_string(),
        content_type: ContentType::Json
    },
    consumer_group_id = "test-group",
    bootstrap_servers = bootstrap_servers,
    handlers = {
        entity_created_event_handler: EntityCreatedEventHandler = EntityCreatedEventHandler {}
    }
);
``` 

This would elminate the need for `generate_handler_types_enum` and for the handlers vector, and it would make it possible to have the entire handlers implementation done statically at compile time, without the need for the heap (vector)

### LINKED ISSUE #11: `event_id` generates a new id on ever call
In https://github.com/ene-rs/ene-kafka/blob/main/ene_kafka_derive/src/cloud_event.rs you can see that the `event_id` will generate a new UUID on every call. 

It would be better to extend the macro fields to have an `id` field, which can be a field of the event, similarly to how it is in the kafka macro. 
```rust
#[derive(KafkaMessage, Serialize, CloudEvent, Debug, Deserialize, DeserializeFrom)]
#[kafka(topic = "test", serde = Json, key = entity_id, headers = CloudEvent)]
#[cloud_event(
    content_type = "application/json",
    version = "1.0",
    event_type = "com.ene.entity.created.v1",
    event_source = "https://ene-kafka.com/docs/cloudevents/entity/created",
    id = entity_id
)]
struct EntityCreated {
    pub entity_id: i64,
    pub organisation_id: i64,
}
```

### LINKED ISSUE #12: rdkafka as a feature flag
The goal of ene-kafka is to make it easier to switch between different Kafka implementations without affecting the interface. This should help with the extensibility of ene-kafka, and can be especially useful when a stable, rust-native, kafka implementation comes to light. Right now, ene-kafka defaults all the inner implementations to rdkafka. It wouldve been easier to have the rdkafka implementation as a feature flag? even if it's currently the only available implementation.

### PR DESCRIPTION
**Pull request by Abdullahsab3**
This PR improves the consumer interface, as described in https://github.com/ene-rs/ene-kafka/issues/10 
It also fixes https://github.com/ene-rs/ene-kafka/issues/11 
Starting from this PR there will be a feature flag `rdkafka`  which will be the default feature for now

closes  https://github.com/ene-rs/ene-kafka/issues/10 
closes https://github.com/ene-rs/ene-kafka/issues/11 
closes https://github.com/ene-rs/ene-kafka/issues/12

### CODE REVIEW

File: ene_kafka/src/dispatchers/mod.rs [hunk 1]
```diff
@@ -32,26 +32,25 @@ macro_rules! generate_handler_types_enum {
...
-            for handler in self.handlers.iter() {
-                match handler {
-                    $(HandlerTypes::$handler(handler) => {
-                        if ene_kafka::handlers::EventHandler::can_handle(handler, event)? {
-                            ene_kafka::handlers::EventHandler::deserialize_and_handle(handler, event).await?;
-                        }
-                    }),*
+            use ene_kafka::handlers::EventHandler;
+            $(
+                if self.$handler_name.can_handle(event)? {
```
Comment (Abdullahsab3) [inline ene_kafka/src/dispatchers/mod.rs:32]: This will change the semantics of how handlers no work. This will make it possible for the same event to pass through multiple handlers. I think personally that it's a nice to have, but it can also introduce subtle bugs

Comment (Abdullahsab3) [reply ene_kafka/src/dispatchers/mod.rs:32]: Update: I changed my mind. it would be tricky to know what failed.

**Comment by Abdullahsab3** [comment]
This PR introduces a new consumer interface. The old interface will be broken and is no longer supported
